<?php

function getUserAccess($user) {

    if ($user['age'] < 18) {
        return $user['name'] . " is a minor.";

    } elseif ($user['role'] === "admin") {
        return $user['name'] . " has full admin access.";

    } elseif ($user['role'] === "editor") {
        return $user['name'] . " can edit content.";

    } else {
        return $user['name'] . " is a standard user.";
    }
}

$result = "";

if ($_SERVER["REQUEST_METHOD"] === "POST") {

    if (isset($_POST['name']) && isset($_POST['age']) && isset($_POST['role'])) {

        $user = [
            "name" => $_POST['name'],
            "age"  => (int)$_POST['age'],
            "role" => $_POST['role']
        ];

        $result = getUserAccess($user);
    }
}

?>

<!DOCTYPE html>
<html>
<head>
    <title>User Access Form</title>
</head>
<body>

<h2>User Access System</h2>

<form method="POST" action="">
    <label>Name:</label>
    <input type="text" name="name" required>
    <br><br>

    <label>Age:</label>
    <input type="number" name="age" required>
    <br><br>

    <label>Role:</label>
    <select name="role">
        <option value="admin">Admin</option>
        <option value="editor">Editor</option>
        <option value="subscriber">Subscriber</option>
    </select>
    <br><br>

    <button type="submit">Submit</button>
</form>

<br>

<?php
if ($result !== "") {
    echo "<strong>Result: </strong>" . $result;
}
?>

</body>
</html>

<!-- When you open `form.php` in your browser, 
your browser (called the **client**) sends an **HTTP request** 
to the PHP server (like XAMPP running on your system). 
The server receives this request and sees that
 it’s a `.php` file, so before sending anything 
 back, it executes the PHP code on the server side. 
 The browser never sees the PHP code — it only receives the
final HTML output generated by PHP. When you first open the page, 
  the request method is usually **GET**, which simply means “give me  this page.” When you fill the form and click submit, the browser sends
   another HTTP request, but this time using the **POST** method because
    the form has `method="POST"`. PHP automatically collects the submitted
     form data into a predefined **superglobal array** called 
     `$_POST`, which is an associative array containing 
     values like name, age, and role. Another predefined
      superglobal, `$_SERVER`, contains request-related information, such as `$_SERVER["REQUEST_METHOD"]`, which tells PHP whether the request is GET or POST. We use `isset()` (a built-in PHP function) to safely check if form values exist before using them, so we avoid “undefined index” errors. Since form data is always received as strings, we sometimes use **type casting** like `(int)` to convert values (for example, age) into integers for proper comparisons. In short: the browser sends a request, the PHP server processes it using built-in superglobals like `$_POST` and `$_SERVER`, executes your custom logic (like the `getUserAccess()` function you wrote), and then sends the final result back to the browser as HTML. -->


      <!-- In this case, frontend and backend are written in the same file (form.php). When the browser (client) first requests the page, it sends an HTTP GET request to the server asking for the PHP file. The server receives this request and executes the PHP code on the server side. After executing, PHP generates HTML and sends only the final HTML output back to the browser. The browser never sees the PHP code — it only renders the HTML it receives.

Inside that PHP file, we also have backend logic written for handling form data. However, that part does not run immediately during the first page load because the request method is GET.

When the user fills the form and clicks submit, the browser sends another HTTP request — this time a POST request (because the form uses method="POST"). The server receives this POST request, and PHP automatically collects the submitted form data inside a predefined associative array called $_POST.

Now PHP checks:

What type of request is this? (using $_SERVER["REQUEST_METHOD"])

Is it POST?

Are required fields set? (using isset())

If everything is valid, PHP builds a user array from the submitted data and passes it to our custom function (like getUserAccess()). That function processes the data based on logic we defined (age check, role check, etc.), returns a result, and then PHP outputs that result back to the browser.

So the full cycle is:

Browser (Client)
→ Sends GET request
→ Server runs PHP
→ Sends HTML

User fills form
→ Browser sends POST request
→ PHP collects data in $_POST
→ Custom logic runs
→ Result sent back to browser

This is how frontend and backend work together in a basic PHP application. -->